### ISSUE TITLE
Modal dialogs are not large enough to read content

### ISSUE THREAD

**Issue by Clef-0** [finchMFG/DewritoHub-2.0#10]
![image](https://user-images.githubusercontent.com/10343775/64077661-5e5b1b80-ccca-11e9-908a-4b03dbb622af.png)

Tested on Firefox 68.0.2 and Edge 44.18362.267.0 and affects both.

**Comment by finchMFG** [comment]
Ouch! I'll get on that right away! Cheers for the report!
